language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: SCHEME="SwiftyBeaverProvider"
    - os: osx
      osx_image: xcode9
      env: SCHEME="SwiftyBeaverProvider-Package"
      
before_install:
    - brew tap vapor/tap;
    - brew update;
    - brew install vapor;

script:
    - swift build
    - swift build -c release
    - swift package generate-xcodeproj
    - xcodebuild -scheme $SCHEME -enableCodeCoverage YES test | xcpretty  # instead of swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
